export const ROUTES = {
  HOME: "/",
  MAIN: "/main",
  DETAILS: "/details/:id",
  SIGN_UP: "/sign",
  LOGIN: "/login",
  LANDING: "/landing",
  FORGOT_PASSWORD: "/forgot-password",
  INFO: "/info",
  REGISTER: "/register",
  EDIT_REGISTER: "/register/edit/:id",
  RESET_PASSWORD: "/reset-password/:token",
  ADMIN: "/admin",
  NOT_FOUND: "*",
};
